/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public\model\PinkCharacter.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/PinkCharacter.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_1" position={[-0.033, -0.005, -0.944]} scale={0.5}>
          <group name="Armature" position={[0, -0.32, -0.573]} rotation={[Math.PI / 2, 0, 0]} scale={1.482}>
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh name="10294136_0" geometry={nodes['10294136_0'].geometry} material={materials['Material.005']} skeleton={nodes['10294136_0'].skeleton} />
            <skinnedMesh name="Aviator_Glasses" geometry={nodes.Aviator_Glasses.geometry} material={materials['Material.007']} skeleton={nodes.Aviator_Glasses.skeleton} />
            <skinnedMesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Skin} skeleton={nodes.Cylinder.skeleton} />
            <skinnedMesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Skin} skeleton={nodes.Cylinder001.skeleton} />
            <skinnedMesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials['Material.002']} skeleton={nodes.defaultMaterial.skeleton} />
            <skinnedMesh name="Eyes" geometry={nodes.Eyes.geometry} material={materials['Eyes and Noes']} skeleton={nodes.Eyes.skeleton} />
            <skinnedMesh name="Face" geometry={nodes.Face.geometry} material={materials.Skin} skeleton={nodes.Face.skeleton} />
            <skinnedMesh name="Face001" geometry={nodes.Face001.geometry} material={materials.Mouth} skeleton={nodes.Face001.skeleton} />
            <skinnedMesh name="Hoodie" geometry={nodes.Hoodie.geometry} material={materials.Material} skeleton={nodes.Hoodie.skeleton} />
            <skinnedMesh name="image_(11)_(1)_(1)" geometry={nodes['image_(11)_(1)_(1)'].geometry} material={materials.Logo} skeleton={nodes['image_(11)_(1)_(1)'].skeleton} />
            <skinnedMesh name="image_(11)_(1)_(1)001" geometry={nodes['image_(11)_(1)_(1)001'].geometry} material={materials.Logo} skeleton={nodes['image_(11)_(1)_(1)001'].skeleton} />
            <skinnedMesh name="neck" geometry={nodes.neck.geometry} material={materials.Skin} skeleton={nodes.neck.skeleton} />
            <skinnedMesh name="Nose" geometry={nodes.Nose.geometry} material={materials['Eyes and Noes']} skeleton={nodes.Nose.skeleton} />
            <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Skin} skeleton={nodes.Object_17.skeleton} />
            <skinnedMesh name="Object_17001" geometry={nodes.Object_17001.geometry} material={materials.Skin} skeleton={nodes.Object_17001.skeleton} />
            <skinnedMesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Sneeker} skeleton={nodes.Plane001.skeleton} />
            <skinnedMesh name="Plane076" geometry={nodes.Plane076.geometry} material={materials.Sneeker} skeleton={nodes.Plane076.skeleton} />
            <skinnedMesh name="Sharp_Cuban_Link_Chain002" geometry={nodes.Sharp_Cuban_Link_Chain002.geometry} material={materials['Gold Chain']} skeleton={nodes.Sharp_Cuban_Link_Chain002.skeleton} />
            <skinnedMesh name="Shirt" geometry={nodes.Shirt.geometry} material={nodes.Shirt.material} skeleton={nodes.Shirt.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/PinkCharacter.glb')
